import { getAllPosts } from "@/lib/blog"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"

export const metadata = {
  title: "~/theShell/blog",
  description: "Read all blog posts from theShell",
}

export default async function BlogPage() {
  const posts = await getAllPosts()

  return (
    <div className="min-h-screen terminal-bg text-green-400">
      <header className="border-b-2 border-green-400 bg-black/90">
        <div className="max-w-4xl mx-auto px-6 py-8">
          <div className="font-mono text-center">
            <h1 className="text-2xl md:text-4xl font-bold text-green-400 mb-2">~/theShell/blog$</h1>
            <p className="text-sm text-green-300">&gt; All memories loaded... Ready to explore.</p>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-12 font-mono">
        <div className="mb-12">
          <h2 className="text-xl font-bold text-green-400 mb-8">&gt; ls -la ~/memories/ ({posts.length} files)</h2>

          {posts.length === 0 ? (
            <div className="bg-black/80 border-2 border-green-600 p-8 text-center">
              <p className="text-green-300 mb-4">&gt; No blog posts found...</p>
              <p className="text-green-500 text-sm">&gt; Add markdown files to content/posts/ directory</p>
            </div>
          ) : (
            <div className="grid gap-6">
              {posts.map((post) => (
                <Link key={post.slug} href={`/blog/${post.slug}`}>
                  <Card className="group bg-black/80 border-2 border-green-600 hover:border-green-400 transition-all duration-300 hover:shadow-lg hover:shadow-green-400/30 cursor-pointer h-full">
                    <CardHeader>
                      <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
                        <Badge className="bg-green-600 text-black font-mono text-xs font-bold border border-green-400">
                          {post.category}
                        </Badge>
                        <span className="font-mono text-xs text-green-500">{post.readTime}</span>
                      </div>
                      <CardTitle className="font-mono text-lg font-bold text-green-400 group-hover:text-green-300 transition-colors">
                        {post.title}
                      </CardTitle>
                      <CardDescription className="font-mono text-green-500 text-xs">{post.date}</CardDescription>
                    </CardHeader>
                    <CardContent>
                      <p className="font-mono text-green-300 text-sm leading-relaxed">{post.excerpt}</p>
                    </CardContent>
                  </Card>
                </Link>
              ))}
            </div>
          )}
        </div>
      </main>

      <footer className="border-t-2 border-green-400 bg-black/90 mt-20">
        <div className="max-w-4xl mx-auto px-6 py-8 text-center">
          <Link href="/">
            <Button
              variant="ghost"
              className="font-mono text-green-400 hover:text-green-300 hover:bg-green-900/30 font-bold text-sm mb-4"
            >
              &gt; cd ~/
            </Button>
          </Link>
          <p className="font-mono text-green-500 text-sm">
            &gt; © 2025 Terminal Blog v1.0 | Generated By{" "}
            <a
              href="https://v0.app"
              target="_blank"
              rel="noopener noreferrer"
              className="text-green-400 hover:text-green-300 underline transition-colors"
            >
              v0
            </a>
          </p>
        </div>
      </footer>
    </div>
  )
}
